"""CivicCore shared platform package for the CivicSuite municipal suite.

Current development-line surface includes migrations, a shared SQLAlchemy
``Base``, LLM helpers, hash-chained audit primitives, source/provenance
metadata contracts, offline import/export manifests, export bundle helpers,
local city profile configuration, and small auth helpers for protected or
mixed public/staff FastAPI routes, including bearer-token and trusted-header
reverse-proxy bridges, live connector sync retry and circuit-breaker
primitives, connector delta planning, reusable mock-city proof contracts, shared
document ingestion with parser dispatch, sentence-aware chunking, local Ollama
embeddings, pgvector-backed chunk storage, startup config validation helpers
for placeholder-free module settings, and shared cron schedule validation
helpers for module background jobs.
CivicCore is a library, not an end-user application.
"""

from __future__ import annotations

__version__ = "1.2.0"

from civiccore.audit import (
    AuditActor,
    AuditEvent,
    AuditHashChain,
    AuditSubject,
    PersistedAuditLogEntry,
    ZERO_HASH,
    canonical_audit_actor_id,
    canonical_audit_details,
    canonical_audit_timestamp,
    compute_persisted_audit_hash,
    verify_persisted_audit_chain,
)
from civiccore.city_profile import (
    CityProfile,
    DepartmentProfile,
    DeploymentProfile,
    ModuleEnablement,
    load_city_profile,
)
from civiccore.connectors import (
    ConnectorImportError,
    ExportManifest,
    ImportedAgendaItem,
    ImportedMeeting,
    ImportManifest,
    ManifestFile,
    ManifestValidationError,
    SUPPORTED_CONNECTORS,
    DELTA_QUERY_PARAMS,
    SyncCircuitPolicy,
    SyncCircuitState,
    SyncHealthStatus,
    SyncOperatorStatus,
    SyncRetryExhausted,
    SyncRetryPolicy,
    SyncRunResult,
    SyncSourceStatus,
    VendorDeltaRequestPlan,
    apply_sync_run_result,
    build_sync_operator_status,
    build_sync_source_status,
    compute_retry_delay,
    compute_sync_health_status,
    import_meeting_payload,
    plan_vendor_delta_request,
    validate_manifest,
    with_http_retry,
)
from civiccore.exports import (
    BundleFile,
    ExportBundle,
    build_sha256sums,
    validate_bundle,
    write_manifest,
)
from civiccore.ingest import (
    CitedSentence,
    CitationValidationError,
    DataSource,
    DiscoveredRecord,
    Document,
    DocumentChunk,
    FetchedDocument,
    HealthCheckResult,
    HealthStatus,
    IngestionStatus,
    SourceMaterial,
    SourceType,
    compute_file_hash,
    ingest_bytes,
    ingest_directory,
    ingest_file,
    ingest_structured_record,
    register_handler,
    validate_cited_sentences,
)
from civiccore.notifications import (
    DeadlinePlan,
    NoticeComplianceResult,
    NoticeComplianceWarning,
    SPECIAL_NOTICE_TYPES,
    build_deadline_plan,
    evaluate_notice_compliance,
)
from civiccore.onboarding import (
    DEFAULT_PROFILE_FIELDS,
    OnboardingField,
    OnboardingProgress,
    completed_profile_fields,
    compute_onboarding_status,
    next_profile_prompt,
    parse_profile_answer,
)
from civiccore.provenance import (
    CitationTarget,
    DocumentMetadata,
    ProvenanceBundle,
    SourceKind,
    SourceReference,
)
from civiccore.security import (
    AtRestDecryptionError,
    ConfigValidationError,
    build_fernet,
    decrypt_json,
    encrypt_json,
    extract_odbc_host,
    is_blocked_host,
    is_encrypted,
    is_trusted_proxy_ip,
    looks_like_placeholder,
    normalize_allowlist,
    normalize_trusted_proxy_cidrs,
    parse_csv_setting,
    validate_fernet_key_setting,
    validate_odbc_connection_string,
    validate_password_setting,
    validate_secret_setting,
    validate_url_host,
)
from civiccore.search import (
    access_level_allows,
    filter_records_by_access_level,
    normalize_access_value,
    normalize_access_values,
    normalize_search_query,
    normalize_search_text,
    reciprocal_rank_fusion,
    roles_grant_access,
    search_text_matches_query,
)
from civiccore.scheduling import (
    UTC,
    compute_next_sync_at,
    min_interval_minutes,
    validate_cron_expression,
)
from civiccore.release_provenance import (
    ATTESTATION_SCHEMA_VERSION,
    FixtureProvenanceClient,
    GitHubProvenanceClient,
    ProvenanceError,
    build_release_attestation,
    canonical_json_bytes,
    expected_workflow_identity,
    load_attestation,
    run_fixtures,
    verify_release_provenance,
)
from civiccore.verification import normalized_text_sha256, validate_release_browser_evidence

__all__ = [
    "__version__",
    "UTC",
    "AuditActor",
    "AuditEvent",
    "AuditHashChain",
    "AuditSubject",
    "PersistedAuditLogEntry",
    "ZERO_HASH",
    "canonical_audit_actor_id",
    "canonical_audit_details",
    "canonical_audit_timestamp",
    "compute_persisted_audit_hash",
    "compute_next_sync_at",
    "verify_persisted_audit_chain",
    "SourceKind",
    "SourceReference",
    "CitationTarget",
    "DocumentMetadata",
    "ProvenanceBundle",
    "ConnectorImportError",
    "ImportManifest",
    "ExportManifest",
    "ImportedAgendaItem",
    "ImportedMeeting",
    "ManifestFile",
    "ManifestValidationError",
    "SUPPORTED_CONNECTORS",
    "DELTA_QUERY_PARAMS",
    "SyncCircuitPolicy",
    "SyncCircuitState",
    "SyncHealthStatus",
    "SyncOperatorStatus",
    "SyncRetryExhausted",
    "SyncRetryPolicy",
    "SyncRunResult",
    "SyncSourceStatus",
    "VendorDeltaRequestPlan",
    "apply_sync_run_result",
    "build_sync_operator_status",
    "build_sync_source_status",
    "compute_retry_delay",
    "compute_sync_health_status",
    "import_meeting_payload",
    "plan_vendor_delta_request",
    "validate_manifest",
    "with_http_retry",
    "BundleFile",
    "ExportBundle",
    "build_sha256sums",
    "validate_bundle",
    "write_manifest",
    "CitedSentence",
    "CitationValidationError",
    "DataSource",
    "DiscoveredRecord",
    "Document",
    "DocumentChunk",
    "DeadlinePlan",
    "NoticeComplianceResult",
    "NoticeComplianceWarning",
    "SPECIAL_NOTICE_TYPES",
    "build_deadline_plan",
    "evaluate_notice_compliance",
    "DEFAULT_PROFILE_FIELDS",
    "CityProfile",
    "DepartmentProfile",
    "DeploymentProfile",
    "FetchedDocument",
    "HealthCheckResult",
    "HealthStatus",
    "IngestionStatus",
    "ModuleEnablement",
    "OnboardingField",
    "OnboardingProgress",
    "access_level_allows",
    "completed_profile_fields",
    "compute_onboarding_status",
    "decrypt_json",
    "filter_records_by_access_level",
    "encrypt_json",
    "extract_odbc_host",
    "AtRestDecryptionError",
    "ConfigValidationError",
    "build_fernet",
    "is_blocked_host",
    "is_encrypted",
    "is_trusted_proxy_ip",
    "looks_like_placeholder",
    "load_city_profile",
    "normalize_access_value",
    "normalize_access_values",
    "normalize_allowlist",
    "normalize_trusted_proxy_cidrs",
    "parse_csv_setting",
    "next_profile_prompt",
    "normalize_search_query",
    "normalize_search_text",
    "min_interval_minutes",
    "parse_profile_answer",
    "roles_grant_access",
    "search_text_matches_query",
    "reciprocal_rank_fusion",
    "SourceMaterial",
    "SourceType",
    "compute_file_hash",
    "ingest_bytes",
    "ingest_directory",
    "ingest_file",
    "ingest_structured_record",
    "register_handler",
    "validate_cited_sentences",
    "validate_cron_expression",
    "validate_fernet_key_setting",
    "validate_odbc_connection_string",
    "validate_password_setting",
    "validate_secret_setting",
    "normalized_text_sha256",
    "validate_url_host",
    "validate_release_browser_evidence",
    "FixtureProvenanceClient",
    "GitHubProvenanceClient",
    "ProvenanceError",
    "ATTESTATION_SCHEMA_VERSION",
    "canonical_json_bytes",
    "build_release_attestation",
    "expected_workflow_identity",
    "load_attestation",
    "run_fixtures",
    "verify_release_provenance",
]
