import { expect, test } from "@playwright/test";

test("city workflow pages expose real local task controls", async ({ page }) => {
  await page.goto("/");

  await page.getByRole("button", { name: /Meetings & Notices/ }).click();
  await expect(page.getByRole("heading", { name: "Meeting Bodies" })).toBeVisible();
  await expect(page.getByLabel("Meeting body name")).toBeVisible();
  await expect(page.getByLabel("Body type")).toBeVisible();
  await expect(page.getByLabel("Body statutory basis")).toBeVisible();
  await expect(page.getByLabel("Meeting cadence")).toBeVisible();
  await expect(page.getByLabel("Default notice days")).toBeVisible();
  await expect(page.getByLabel("Quorum rule")).toBeVisible();
  await expect(page.getByRole("button", { name: "Save Meeting Body" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Member Roster" })).toBeVisible();
  await expect(page.getByLabel("Roster body")).toBeVisible();
  await expect(page.getByLabel("Member name")).toBeVisible();
  await expect(page.getByLabel("Member role")).toBeVisible();
  await expect(page.getByLabel("Term start")).toBeVisible();
  await expect(page.getByLabel("Term end")).toBeVisible();
  await expect(page.getByLabel("Member email")).toBeVisible();
  await expect(page.getByRole("button", { name: "Save Member" })).toBeDisabled();
  await expect(page.getByRole("heading", { name: "Agenda Intake Queue" })).toBeVisible();
  await expect(page.getByLabel("Intake title")).toBeVisible();
  await expect(page.getByLabel("Submitted by")).toBeVisible();
  await expect(page.getByLabel("Department")).toBeVisible();
  await expect(page.getByLabel("Requested meeting date")).toBeVisible();
  await expect(page.getByLabel("Intake summary")).toBeVisible();
  await expect(page.getByLabel("Source or citation")).toBeVisible();
  await expect(page.getByRole("button", { name: "Submit Agenda Intake" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Review Agenda Intake" })).toBeVisible();
  await expect(page.getByLabel("Readiness decision")).toBeVisible();
  await expect(page.getByLabel("Clerk review note")).toBeVisible();
  await expect(page.getByRole("button", { name: "Review Agenda Intake" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Promote To Agenda" })).toBeDisabled();
  await expect(page.getByRole("heading", { name: "Prepare Meeting" })).toBeVisible();
  await expect(page.getByLabel("Meeting body", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Create Meeting" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Create Meeting" })).toBeDisabled();
  await expect(page.getByLabel("Notice meeting type")).toBeVisible();
  await expect(page.getByLabel("Statutory notice basis")).toBeVisible();
  await expect(page.getByLabel("Notice deadline")).toBeVisible();
  await expect(page.getByLabel("Notice time zone")).toBeVisible();
  await expect(page.getByLabel("Clerk has reviewed and approved the notice checklist")).toBeVisible();
  await expect(page.getByLabel("Actual posting date")).toBeVisible();
  await expect(page.getByLabel("Notice posting location")).toBeVisible();
  await expect(page.getByLabel("Notice posting method")).toBeVisible();
  await expect(page.getByLabel("Posting confirmation")).toBeVisible();
  await expect(page.getByRole("button", { name: "Add Code Handoff" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve Notice Checklist" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Mark Notice Ready" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Export Packet" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Staff Reports" })).toBeVisible();
  await expect(page.getByLabel("Recommendation")).toBeVisible();
  await expect(page.getByLabel("Background")).toBeVisible();
  await expect(page.getByLabel("Analysis")).toBeVisible();
  await expect(page.getByLabel("Fiscal impact")).toBeVisible();
  await expect(page.getByLabel("Alternatives considered")).toBeVisible();
  await expect(page.getByLabel("Prior actions")).toBeVisible();
  await expect(page.getByLabel("Prepared by")).toBeVisible();
  await expect(page.getByRole("button", { name: "Save Staff Report" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Packet Attachments" })).toBeVisible();
  await expect(page.getByLabel("Attachment title")).toBeVisible();
  await expect(page.getByLabel("Attachment source file path")).toBeVisible();
  await expect(page.getByLabel("Attachment citation")).toBeVisible();
  await expect(page.getByLabel("Packet section")).toBeVisible();
  await expect(page.getByLabel("Attachment access")).toBeVisible();
  await expect(page.getByRole("button", { name: "Attach Packet File" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Exports Folder" })).toBeVisible();
  await expect(page.getByLabel("Closed-session statutory basis")).toBeVisible();
  await expect(page.getByLabel("Closed-session topics")).toBeVisible();
  await expect(page.getByLabel("Closed-session attendees")).toBeVisible();
  await expect(page.getByLabel("Entered closed session")).toBeVisible();
  await expect(page.getByLabel("Exited closed session")).toBeVisible();
  await expect(page.getByLabel("Reconvene statement")).toBeVisible();
  await expect(page.getByLabel("Staff-only notes reference")).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Closed Session" })).toBeVisible();
  await expect(page.getByLabel("Motion text")).toBeVisible();
  await expect(page.getByLabel("Moved by")).toBeVisible();
  await expect(page.getByLabel("Seconded by")).toBeVisible();
  await expect(page.getByLabel("Motion disposition")).toBeVisible();
  await expect(page.getByLabel("Linked vote reference")).toBeVisible();
  await expect(page.getByLabel("Roll-call motion")).toBeVisible();
  await expect(page.getByLabel("Roll-call member")).toBeVisible();
  await expect(page.getByLabel("Roll-call vote")).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Motion" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Roll Call Vote" })).toBeDisabled();
  await expect(page.getByLabel("Action owner")).toBeVisible();
  await expect(page.getByLabel("Action due date")).toBeVisible();
  await expect(page.getByLabel("Action status")).toBeVisible();
  await expect(page.getByLabel("Action source")).toBeVisible();
  await expect(page.getByRole("button", { name: "Add Action Item" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Resident Comment" })).toBeVisible();
  await expect(page.getByLabel("Minutes signed by")).toBeVisible();
  await expect(page.getByLabel("Signature attestation")).toBeVisible();
  await expect(page.getByRole("button", { name: "Sign Minutes" })).toBeVisible();
  await expect(page.getByLabel("Adopted item type")).toBeVisible();
  await expect(page.getByLabel("Adopted title")).toBeVisible();
  await expect(page.getByLabel("Adopted text")).toBeVisible();
  await expect(page.getByLabel("Effective date")).toBeVisible();
  await expect(page.getByLabel("Codification section hint")).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Adopted Ordinance/Resolution" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Generate Local AI Minutes" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Minute Citations" })).toBeVisible();
  await expect(page.getByLabel("Minutes sentence or excerpt")).toBeVisible();
  await expect(page.getByLabel("Citation source type")).toBeVisible();
  await expect(page.getByLabel("Citation source reference")).toBeVisible();
  await expect(page.getByLabel("Citation note")).toBeVisible();
  await expect(page.getByLabel("Citation access")).toBeVisible();
  await expect(page.getByRole("button", { name: "Add Minute Citation" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Adopt Minutes" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Archive Public Record" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Public Comment Review" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Mark Reviewed" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Redact Comment" })).toBeDisabled();
  await expect(page.getByText("No local meetings have been created yet.")).toBeVisible();
  await expect(page.getByText("No agenda intake items are waiting for clerk review.")).toBeVisible();
  await expect(page.getByText("No CivicCode handoffs are waiting for the clerk.")).toBeVisible();

  await page.getByRole("button", { name: /Records Requests/ }).click();
  await expect(page.getByRole("heading", { name: "Request Intake" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Create Request" })).toBeVisible();
  await expect(page.getByLabel("Deadline basis")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Scope & Search" })).toBeVisible();
  await expect(page.getByLabel("Fee line description")).toBeVisible();
  await expect(page.getByLabel("Fee schedule or policy basis")).toBeVisible();
  await expect(page.getByLabel("Fee line amount")).toBeVisible();
  await expect(page.getByLabel("Fee waiver reason")).toBeVisible();
  await expect(page.getByLabel("Records search query")).toBeVisible();
  await expect(page.getByLabel("Searched locations")).toBeVisible();
  await expect(page.getByLabel("Search result title")).toBeVisible();
  await expect(page.getByLabel("Search result citation")).toBeVisible();
  await expect(page.getByLabel("Search result summary")).toBeVisible();
  await expect(page.getByLabel("Exemption source")).toBeVisible();
  await expect(page.getByLabel("Exemption category")).toBeVisible();
  await expect(page.getByLabel("Staff finding")).toBeVisible();
  await expect(page.getByLabel("Decision", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Decision basis")).toBeVisible();
  await expect(page.getByLabel("Exemption reviewer")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Request Messages" })).toBeVisible();
  await expect(page.getByLabel("Message to requester")).toBeVisible();
  await expect(page.getByRole("button", { name: "Add Request Message" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Request Documents" })).toBeVisible();
  await expect(page.getByLabel("Document title")).toBeVisible();
  await expect(page.getByLabel("Source file path")).toBeVisible();
  await expect(page.getByLabel("Document citation")).toBeVisible();
  await expect(page.getByRole("button", { name: "Attach Document" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Set Deadline" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Assign" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Request Clarification" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Search" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save Search Session" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Add Exemption Review" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save Exemption Decision" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Estimate Fee" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Add Fee Line" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Waive Fee" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Response & Release" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Generate Local AI Draft" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve Response" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Build Release Package" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Export Response" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Mark Fulfilled" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Close Request" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Exports Folder" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Notification Outbox" })).toBeVisible();
  await expect(page.getByText("No local records notifications have been created yet.")).toBeVisible();

  await page.getByRole("button", { name: /Code & Ordinances/ }).click();
  await expect(page.getByRole("heading", { name: "Import Code Source" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Import Source" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Publish Source", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Unpublish Source", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Exports Folder" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Codifier Sync" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Sync", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Record Sync Failure" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Retry Sync" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Mark Stale" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Guidance & Summary" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Generate Local AI Guidance" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save Guidance Draft" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve Guidance" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Create Clerk Handoff" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Ask Code Question" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Answer Code Question" })).toBeVisible();

  await page.getByRole("button", { name: /Search City Knowledge/ }).click();
  await expect(page.getByRole("heading", { name: "Local Search" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Search Local Data" })).toBeVisible();
  await expect(page.getByText("No local search results yet.")).toBeVisible();
  await expect(page.locator("main").getByText("Scaffold")).toHaveCount(0);
});

test("resident public surface hides staff workflow controls", async ({ page }) => {
  await page.goto("/");

  await page.getByRole("tab", { name: "Resident/Public" }).click();

  await page.getByRole("button", { name: /Meetings & Notices/ }).click();
  await expect(page.getByRole("heading", { name: "Public Meeting Materials" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Submit Public Comment" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Submit Public Comment" })).toBeDisabled();
  await expect(page.getByText("No posted public meeting is open for comment")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Prepare Meeting" })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Agenda Intake Queue" })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Review Agenda Intake" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Submit Agenda Intake" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Review Agenda Intake" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Promote To Agenda" })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Public Comment Review" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Redact Comment" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Save Meeting Body" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Create Meeting" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Add Code Handoff" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Attach Packet File" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Record Motion" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Add Minute Citation" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Archive Public Record" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Open Exports Folder" })).toHaveCount(0);

  await page.getByRole("button", { name: /Records Requests/ }).click();
  await expect(page.getByRole("heading", { name: "Public Records Requests" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Submit Public Records Request" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Submit Records Request" })).toBeVisible();
  await expect(page.getByLabel("Request number")).toBeVisible();
  await expect(page.getByLabel("Submitted contact")).toBeVisible();
  await expect(page.getByLabel("Message to records staff")).toBeVisible();
  await expect(page.getByRole("button", { name: "Check Request Status" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Send Request Message" })).toBeVisible();
  await expect(page.getByText("Pending public intake appears only after the request number and submitted contact match.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Request Intake" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Create Request" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Approve Response" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Export Response" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Mark Fulfilled" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Open Exports Folder" })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Notification Outbox" })).toHaveCount(0);
  await page.getByLabel("Your name").fill("Morgan Lee");
  await page.getByLabel("Email or phone").fill("morgan@example.gov");
  await page.getByLabel("Records requested").fill("Emails and invoices about the river trail grant");
  await page.getByRole("button", { name: "Submit Records Request" }).click();
  await expect(page.getByText("Desktop app required")).toBeVisible();

  await page.getByRole("button", { name: /Code & Ordinances/ }).click();
  await expect(page.getByRole("heading", { name: "Municipal Code Search" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Ask the Code" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Answer Code Question" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Import Code Source" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Import Source" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Publish Source", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Unpublish Source", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Record Sync", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Approve Guidance" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Create Clerk Handoff" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Open Exports Folder" })).toHaveCount(0);

  await page.getByRole("button", { name: /Search City Knowledge/ }).click();
  await expect(page.getByRole("heading", { name: "Public Search" })).toBeVisible();
  await expect(page.getByText("No public search results yet.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Local Search" })).toHaveCount(0);
  await expect(page.getByText("No local search results yet.")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Search Local Data" })).toHaveCount(0);
});

test("risky city workflow actions require guided review before mutation", async ({ page }) => {
  await page.goto("/");

  await page.getByRole("button", { name: /Meetings & Notices/ }).click();
  await page.getByRole("button", { name: "Archive Public Record" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Archiving Public Record" })).toBeVisible();
  await expect(page.getByText("What will change")).toBeVisible();
  await expect(page.getByText("Who can see it")).toBeVisible();
  await expect(page.getByText("Sources and evidence")).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirm Archive Public Record" })).toBeVisible();
  await expect(page.getByText("Desktop app required")).toHaveCount(0);

  await page.getByRole("button", { name: "Cancel Review" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Archiving Public Record" })).toHaveCount(0);

  await page.getByRole("button", { name: "Generate Local AI Minutes" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Generating Minutes Draft" })).toBeVisible();
  await expect(page.getByText("Uses the verified local AI model to draft internal meeting minutes")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Attach Packet File" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Attaching Packet File" })).toBeVisible();
  await expect(page.getByText("Attachment title is required.")).toBeVisible();
  await expect(page.getByText("Attachment source file path is required.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirm Attach Packet File" })).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Add Minute Citation" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Adding Minute Citation" })).toBeVisible();
  await expect(page.getByText("Minutes sentence or excerpt is required.")).toBeVisible();
  await expect(page.getByText("Source reference is required.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirm Add Minute Citation" })).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Approve Notice Checklist" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Approving Notice Checklist" })).toBeVisible();
  await expect(page.getByText("Statutory notice basis is required.")).toBeVisible();
  await expect(page.getByText("Clerk approval is required.")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Mark Notice Ready" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Posting Notice" })).toBeVisible();
  await expect(page.getByText("Approved notice checklist is required.")).toBeVisible();
  await expect(page.getByText("Actual posting date is required.")).toBeVisible();
  await expect(page.getByText("Posting confirmation evidence is required.")).toBeVisible();
  await page.getByRole("button", { name: "Confirm Mark Notice Ready" }).click();
  await expect(page.getByText("Desktop app required")).toBeVisible();

  await page.getByRole("button", { name: /Records Requests/ }).click();
  await page.getByRole("button", { name: "Set Deadline" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Setting Records Deadline" })).toBeVisible();
  await expect(page.getByText("Deadline basis is required.")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Add Request Message" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Adding Request Message" })).toBeVisible();
  await expect(page.getByText("Request message is required.")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Add Fee Line" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Adding Records Fee Line" })).toBeVisible();
  await expect(page.getByText("Fee line description is required.")).toBeVisible();
  await expect(page.getByText("Fee schedule or policy basis is required.")).toBeVisible();
  await expect(page.getByText("Fee line amount is required.")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Waive Fee" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Waiving Records Fee" })).toBeVisible();
  await expect(page.getByText("Fee waiver reason is required.")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();

  await page.getByRole("button", { name: "Generate Local AI Draft" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Generating Records Draft" })).toBeVisible();
  await expect(page.getByText("Uses the verified local AI model to draft an internal response")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();
  await page.getByRole("button", { name: "Approve Response" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Approving Records Response" })).toBeVisible();
  await expect(page.getByText("Internal staff status changes to human-approved")).toBeVisible();

  await page.getByRole("button", { name: /Code & Ordinances/ }).click();
  await page.getByRole("button", { name: "Publish Source", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Review Before Publishing Code Source" })).toBeVisible();
  await expect(page.getByText("Creates CivicCode audit and CivicCore publication-gate entries.")).toBeVisible();
});

test("browser preview refuses persistent city workflow mutations", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: /Meetings & Notices/ }).click();
  await page.getByRole("button", { name: "Save Meeting Body" }).click();
  await expect(page.getByRole("heading", { name: "Review Before Saving Meeting Body" })).toBeVisible();
  await page.getByRole("button", { name: "Confirm Save Meeting Body" }).click();

  await expect(page.getByText("Desktop app required")).toBeVisible();
  await expect(page.getByText("City workflow changes are saved by the Windows desktop app, not the browser preview.")).toBeVisible();
});

test("audit drawer uses local workflow audit language instead of placeholder text", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Audit Trail" }).click();

  await expect(page.getByRole("heading", { name: "Audit Trail" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Publication Gates" })).toBeVisible();
  await expect(page.getByText("No human-approved public records have been published yet.")).toBeVisible();
  await expect(page.getByText("No local workflow actions have been recorded yet.")).toBeVisible();
  await expect(page.getByText("Scaffold")).toHaveCount(0);
});

test("module manager presents the installed city-core package", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: /Settings/ }).click();

  await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "City Profile" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "First Admin" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Local Folders" })).toBeVisible();
  await expect(page.getByLabel("App install folder")).toBeVisible();
  await expect(page.getByLabel("City data folder")).toBeVisible();
  await expect(page.getByLabel("Backup folder")).toBeVisible();
  await expect(page.getByRole("button", { name: "Save Local Folders" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save City Profile" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save First Admin" })).toBeVisible();
  await expect(page.getByLabel("Local passcode")).toBeVisible();
  await expect(page.getByRole("heading", { name: "City Core Modules" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Choose Product Modules" })).toBeVisible();
  await expect(page.getByLabel(/City Core/)).toBeChecked();
  await expect(page.locator('[data-module-toggle="civicrecords-ai"]')).toBeChecked();
  await expect(page.locator('[data-module-toggle="civicclerk"]')).toBeChecked();
  await expect(page.locator('[data-module-toggle="civiccode"]')).toBeChecked();
  await expect(page.locator('[data-module-toggle="civiczone"]')).toBeDisabled();
  await expect(page.getByText("Not ready for Windows Local 1.0")).toBeVisible();
  await page.getByLabel(/Custom/).check();
  await expect(page.getByText("Custom selection will install CivicCore plus 3 selected product modules.")).toBeVisible();
  await page.locator('[data-module-toggle="civicrecords-ai"]').uncheck();
  await expect(page.getByText("Custom selection will install CivicCore plus 2 selected product modules.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Apply Module Selection" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "City Core Package" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Package Profiles" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Module Catalog" })).toBeVisible();
  await expect(page.getByText("Selected profile: City Core. Installed modules: 4. Enabled modules: 4.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "CivicCore" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "CivicRecords AI" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "CivicClerk" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "CivicCode" })).toBeVisible();
  await expect(page.getByText("Backup includes: code workflow history, code exports, code files")).toBeVisible();
  await expect(page.getByRole("button", { name: "Disable CivicCode" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Exports CivicCode" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Check Update CivicCode" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Remove From Profile CivicCode" })).toBeVisible();
  await page.getByRole("button", { name: "Remove From Profile CivicCode" }).click();
  const removeReview = page.locator(".guided-review").filter({ hasText: "Review Before Removing CivicCode From Profile" });
  await expect(removeReview.getByText("Creates a verified local profile backup")).toBeVisible();
  await expect(removeReview.getByText("Writes a backup manifest before updating the local module-selection record")).toBeVisible();
  await page.getByRole("button", { name: "Cancel Review" }).click();
  await page.getByRole("button", { name: "Disable CivicCode" }).click();
  const moduleReview = page.locator(".guided-review").filter({ hasText: "Review Before Disabling CivicCode" });
  await expect(moduleReview.getByRole("heading", { name: "Review Before Disabling CivicCode" })).toBeVisible();
  await expect(moduleReview.getByText("Existing module data remains installed.")).toBeVisible();
  await expect(moduleReview.getByText("Audit trail", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirm Disable Module" })).toBeVisible();
  await expect(page.getByText("Module actions are handled by the Windows desktop app")).toHaveCount(0);
  await page.getByRole("button", { name: "Confirm Disable Module" }).click();
  await expect(page.getByText("Module actions are handled by the Windows desktop app")).toBeVisible();
  await expect(page.getByText("install, update, enable, disable, remove modules, or open local module exports")).toBeVisible();
  await expect(page.getByText("Installed by selected package profile").first()).toBeVisible();
  await expect(page.getByText("Updated through the versioned module manifest").first()).toBeVisible();
  await expect(page.getByText("Allowed after a backup is created").first()).toBeVisible();
  await expect(page.getByText("Removed only after module data backup").first()).toBeVisible();
  await expect(page.getByText("backup-first-module-data-removal")).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Full Suite" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "CivicZone" })).toBeVisible();
  await expect(page.getByText("Package waiting")).toBeVisible();
  await expect(page.getByText("Scaffold")).toHaveCount(0);
});
