"""Shared security primitives extracted for CivicSuite modules."""

from civiccore.security.at_rest import (
    AtRestDecryptionError,
    ENVELOPE_VERSION,
    build_fernet,
    decrypt_json,
    encrypt_json,
    is_encrypted,
)
from civiccore.security.host_validation import (
    BLOCK_REASON,
    BLOCKED_HOSTNAMES,
    BLOCKED_NETWORKS,
    ODBC_HOST_KEYS,
    extract_odbc_host,
    is_blocked_host,
    is_trusted_proxy_ip,
    normalize_allowlist,
    normalize_trusted_proxy_cidrs,
    validate_odbc_connection_string,
    validate_url_host,
)
from civiccore.security.config_validation import (
    ConfigValidationError,
    DEFAULT_INSECURE_FERNET_KEY_VALUES,
    DEFAULT_INSECURE_PASSWORD_VALUES,
    DEFAULT_INSECURE_SECRET_VALUES,
    looks_like_placeholder,
    parse_csv_setting,
    validate_fernet_key_setting,
    validate_password_setting,
    validate_secret_setting,
)

__all__ = [
    "AtRestDecryptionError",
    "BLOCK_REASON",
    "BLOCKED_HOSTNAMES",
    "BLOCKED_NETWORKS",
    "ConfigValidationError",
    "DEFAULT_INSECURE_FERNET_KEY_VALUES",
    "DEFAULT_INSECURE_PASSWORD_VALUES",
    "DEFAULT_INSECURE_SECRET_VALUES",
    "ENVELOPE_VERSION",
    "ODBC_HOST_KEYS",
    "build_fernet",
    "decrypt_json",
    "encrypt_json",
    "extract_odbc_host",
    "is_blocked_host",
    "is_encrypted",
    "is_trusted_proxy_ip",
    "looks_like_placeholder",
    "normalize_allowlist",
    "normalize_trusted_proxy_cidrs",
    "parse_csv_setting",
    "validate_fernet_key_setting",
    "validate_odbc_connection_string",
    "validate_password_setting",
    "validate_secret_setting",
    "validate_url_host",
]
